import type { Metadata } from "next";
import "./styles/globals.scss";
import { Analytics } from "@vercel/analytics/react";
import WebVitals from "./_lib/WebVitals";
import { GoogleTagManager } from "@next/third-parties/google";

interface GTMProps {
  type: string;
  gtmId: string;
}

const gtmProps: GTMProps = {
  type: "text/partytown",
  gtmId: "GTM-M8PS5F6",
};
export const metadata: Metadata = {
  title: "julianaijal.com",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleTagManager {...gtmProps} />
      <body>
        <WebVitals />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
