import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from './_components/Layout';
import Schema from './_lib/Schema';
import Script from "next/script"; 


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>julianaijal.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script
        src="https://unpkg.com/react-scan/dist/install-hook.global.js"
        strategy="beforeInteractive"
      /> */}
      {/* To-do:move to head */}
      <Schema/>
      <Layout />
    </>
  );
};

export default Home;
